# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: just-the-docs/just-the-docs

title: Blog
description: Blog for notes
email: sam.lewallen@gmail.com
# github_username: morsehomology
baseurl: "/blog-just-the-docs"
url: "https://morsehomology.github.io"
permalink: pretty

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
    # Split pages into sections that can be searched individually
    # Supports 1 - 6, default: 2
    heading_level: 2
    # Maximum amount of previews per search result
    # Default: 3
    previews: 2
    # Maximum amount of words to display before a matched word in the preview
    # Default: 5
    preview_words_before: 3
    # Maximum amount of words to display after a matched word in the preview
    # Default: 10
    preview_words_after: 3
    # Set the search token separator
    # Default: /[\s\-/]+/
    # Example: enable support for hyphenated search words
    tokenizer_separator: /[\s/]+/
    # Display the relative url in search results
    # Supports true (default) or false
    rel_url: true
    # Enable or disable the search button that appears in the bottom right corner of every page
    # Supports true or false (default)
    button: false

# theme: "just-the-docs"
plugins:
    - jekyll-feed
    - jekyll-toc

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Define Jekyll collections
collections:
    # Define a collection named "tests", its documents reside in the "_tests" directory
    tests:
        permalink: "/:collection/:path/"
        output: true

just_the_docs:
    # Define which collections are used in just-the-docs
    collections:
        # Reference the "tests" collection
        tests:
            # Give the collection a name
            name: Notes
            # Exclude the collection from the navigation
            # Supports true or false (default)
            # nav_exclude: true
            # Fold the collection in the navigation
            # Supports true or false (default)
            nav_fold: false
            # Exclude the collection from the search
            # Supports true or false (default)
            # search_exclude: true

compress_html:
    blanklines: true
mathjax:
    source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
    config:
        'MathJax.Hub.Config({ tex2jax: { inlineMath: [ ["$","$"], ["\\(","\\)"]
        ], processEscapes: true }})'
        # 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'
# <script type="text/x-mathjax-config">

# </script>

# <script type="text/javascript"
#         src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
# </script>

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: false
# compress_html:
#   clippings: all
#   comments: all
#   endings: all
#   startings: []
#   blanklines: false
#   profile: false
#   # ignore:
#   #   envs: all
